version: 2
jobs:
  build:
    working_directory: ~/project
    docker:
        - image: circleci/openjdk:8-jdk
    steps:
      - checkout:
          path: ~/project
      - restore_cache:
          keys:
            - books-{{ checksum "pom.xml" }}
      - save_cache:
          paths:
            - ~/.m2
          key: books-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - run:
          name: Run Tests
          command: mvn verify
      - run:
          name: Package into jar
          command: mvn clean package
      - run:
          name: Build Docker Image
          command: |
            docker build -t mattgraygithub/books:${CIRCLE_SHA1} .
            docker tag mattgraygithub/books:${CIRCLE_SHA1} mattgraygithub/books:latest
      - run:
          name: Push docker image to Docker Hub
          command: |
              echo "$DOCKER_HUB_PASS" | docker login -u "$DOCKER_HUB_USER_NAME" --password-stdin
              docker push mattgraygithub/books:${CIRCLE_SHA1}
              docker push mattgraygithub/books:latest
      - store_artifacts:
          path: target/classes
          destination: books
