version: 2
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout:
          path: ~/project
      - run: mvn dependency:go-offline
      - run:
          name: Run Tests
          command: mvn verify
      - run:
          name: Package into jar
          command: mvn clean package
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: |
            docker build -t mattgraydh/books:${CIRCLE_SHA1} .
            docker tag mattgraydh/books:${CIRCLE_SHA1} mattgraydh/books:latest
      - run:
          name: Push docker image to Docker Hub
          command: |
            echo "$DOCKER_HUB_PASS" | docker login -u "$DOCKER_HUB_USER_NAME" --password-stdin
            docker push mattgraydh/books:${CIRCLE_SHA1}
            docker push mattgraydh/books:latest
    deploy:
      steps:
        - add_ssh_keys:
            fingerprints:
              - "5e:23:ba:40:77:61:58:c9:c4:2e:cc:1a:44:93:ba:bc"
        - run:
            name: Connect to EC2 instance
            command: ssh ec2-user@ec2-18-212-105-75.compute-1.amazonaws.com

        - run:
            name: Run application
            command: sudo service docker start
