version: 2
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout:
          path: ~/project
      - run: mvn dependency:go-offline
      - run:
          name: Run Tests
          command: mvn verify
      - run:
          name: Package into jar
          command: mvn clean package
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: |
            docker build -t mattgraydh/books:${CIRCLE_SHA1} .
            docker tag mattgraydh/books:${CIRCLE_SHA1} mattgraydh/books:latest
      - run:
          name: Push docker image to Docker Hub
          command: |
            echo "$DOCKER_HUB_PASS" | docker login -u "$DOCKER_HUB_USER_NAME" --password-stdin
            docker push mattgraydh/books:${CIRCLE_SHA1}
            docker push mattgraydh/books:latest
      - run:
          name: Connect to EC2 instance
          command: ssh -i "books.pem" ec2-user@ec2-18-212-105-75.compute-1.amazonaws.com
      - run:
          name: Install docker on EC2 instance
          command: sudo service docker start
      - run:
          name: Run application
          command: sudo docker run -p 80:8080 books:latest
